services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: centro_actividades
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    environment:
      - UV_LINK_MODE=copy
      - UV_PROJECT_ENVIRONMENT=/app/.venv
      - DB_HOST=db
      - DB_NAME=centro_actividades
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv        # Evita que el .venv de Docker sobrescriba el mio o viceversa
      - /app/.uv_cache   # Evita que el .uv_cache de Docker sobrescriba el mio o viceversa

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
