"""agrega tabla salones y salon_id a turnos

Revision ID: 5f3e0656162f
Revises: ed4cedeea7ce
Create Date: 2026-07-06 20:06:40.811413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3e0656162f'
down_revision: Union[str, Sequence[str], None] = 'ed4cedeea7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salones',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salones_id'), 'salones', ['id'], unique=False)
    op.create_index('uq_salones_name_active', 'salones', ['name'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.add_column('turnos', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_turnos_salon_id_salones', 'turnos', 'salones', ['salon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_turnos_salon_id_salones', 'turnos', type_='foreignkey')
    op.drop_column('turnos', 'salon_id')
    op.drop_index('uq_salones_name_active', table_name='salones', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index(op.f('ix_salones_id'), table_name='salones')
    op.drop_table('salones')
    # ### end Alembic commands ###
