name: Revisión Automática (CI)

on:
  pull_request: # Esto hace que se ejecute SOLO cuando alguien abre un PR
    branches:
      - develop
      - main

jobs:
  revisar-codigo:
    runs-on: ubuntu-latest # GitHub nos presta una maquinita con Linux

    steps:
      - name: 📥 Traer el código del PR
        uses: actions/checkout@v4

      - name: ⚡ Instalar 'uv' (La acción mágica)
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Guarda las librerías en caché para volar en el próximo PR

      - name: 📦 Instalar dependencias del proyecto
        run: uv sync

      - name: 🕵️‍♂️ Buscar errores de código (Ruff Linter)
        # El formato 'github' hace que los errores aparezcan comentados directo en la línea de código del PR
        run: uv run ruff check --output-format=github .

      - name: 🎨 Verificar formato de código (Ruff Formatter)
        # El '--check' hace que falle si alguien no corrió 'uv run ruff format .' antes de subirlo
        run: uv run ruff format --check .